name: universal_f_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_swiper_plus: ^2.0.4
  google_places_flutter: ^2.0.9
  http: ^1.2.2
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_datepicker: ^26.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/